services:
    nb:
        image: nb
        environment:
            - JUPYTER_TOKEN=local
        ports:
            - "8000:8888"
        volumes:
            - "./nb:/home/jovyan/nb"

    postgres:
        image: ankane/pgvector
        environment:
          POSTGRES_DB: vector_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        deploy:
            resources:
                limits:
                    memory: 1G

    worker-1:
        image: worker
        depends_on:
          -  "postgres"

    worker-2:
        image: worker
        depends_on:
          -  "postgres"

    master:
        image: master
        command: bash -c "python3 init_db.py && python3 master.py worker-1 worker-2"
        # command: sleep infinity
        volumes:
         - "./data:/data"
        depends_on:
          -  "worker-1"
          -  "worker-2"
