# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workerserver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12workerserver.proto\".\n\x0f\x46ileDataRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\"\'\n\x10StratNameRequest\x12\x13\n\x0bstrat_names\x18\x01 \x03(\t\"\x1e\n\rErrorResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t2u\n\x0cWorkerServer\x12/\n\tStoreFile\x12\x10.FileDataRequest\x1a\x0e.ErrorResponse\"\x00\x12\x34\n\rSetStratNames\x12\x11.StratNameRequest\x1a\x0e.ErrorResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workerserver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEDATAREQUEST']._serialized_start=22
  _globals['_FILEDATAREQUEST']._serialized_end=68
  _globals['_STRATNAMEREQUEST']._serialized_start=70
  _globals['_STRATNAMEREQUEST']._serialized_end=109
  _globals['_ERRORRESPONSE']._serialized_start=111
  _globals['_ERRORRESPONSE']._serialized_end=141
  _globals['_WORKERSERVER']._serialized_start=143
  _globals['_WORKERSERVER']._serialized_end=260
# @@protoc_insertion_point(module_scope)
